In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
import numpy as np
import json

### Loading Datasets

In [3]:
baseline = pd.read_csv("./Heart Disease Prediction/baseline.csv")
ground_truths = pd.read_csv("./Heart Disease Prediction/Ground Truths/07th Feb 2024.csv")
production_run = pd.read_csv("./Heart Disease Prediction/Production Runs/07th Feb 2024.csv")
ground_truths.drop("Unnamed: 0", axis=1, inplace=True)

In [4]:
baseline.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
3,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
4,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0

In [5]:
ground_truths.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
0,63,F,ATA,140,195,0,Normal,179,N,0.0,Up,0
1,53,M,NAP,145,518,0,Normal,130,N,0.0,Flat,1
2,65,M,ASY,160,0,1,ST,122,N,1.2,Flat,1
3,56,M,ASY,130,0,0,LVH,122,Y,1.0,Flat,1
4,54,M,ATA,108,309,0,Normal,156,N,0.0,Up,0

In [6]:
production_run.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target,probs
0,63,F,ATA,140.0,195.0,0.0,Normal,179.0,N,0.0,Up,0,1.0
1,53,M,NAP,145.0,518.0,0.0,Normal,130.0,N,0.0,Flat,1,0.6
2,65,M,ASY,160.0,0.0,1.0,ST,122.0,N,1.2,Flat,1,1.0
3,56,M,ASY,130.0,0.0,0.0,LVH,122.0,Y,1.0,Flat,1,1.0
4,54,M,ATA,108.0,309.0,0.0,Normal,156.0,N,0.0,Up,0,1.0

### Checking the results and fetching per analysis results

In [4]:
from utils import get_results

In [5]:
model_type="Classification"

In [6]:
new_results = get_results(model_name="Heart Disease Prediction", 
                          model_type="Classification",
                          ground_truth=ground_truths, 
                          production_data=production_run.drop('probs', axis=1) if model_type == 'Classification' else production_run, 
                          date="07th Feb 2024.csv", baseline_data=baseline)

{'jsd_value': 0.01, 'js_threshold': 0.2, 'js_status': False} {'psi_value': 0.0, 'psi_threshold': 0.2, 'psi_status': False}

C:\Users\Akshat Mittu\AppData\Roaming\Python\Python38\site-packages\pandas\core\arraylike.py:402: RuntimeWarning:

divide by zero encountered in log

C:\Users\Akshat Mittu\AppData\Roaming\Python\Python38\site-packages\pandas\core\arraylike.py:402: RuntimeWarning:

divide by zero encountered in log

In [8]:
dict1 = {'a': 1, 'b': 4, 1: 4}
dict2 = {'c': 6, 7:8}
dict3 = {4:3, 9:10}
dict2.update(dict3)

In [9]:
dict2

{'c': 6, 7: 8, 4: 3, 9: 10}

In [7]:
new_results

{'Heart Disease Prediction': {'07th Feb 2024.csv': {'Production Data Summary': {'Number of rows': 209,
    'Number of rows without NaN': 171,
    'Number of rows with Nan': 38,
    'Completeness Score': 81.82,
    'Uniqueness Score': 100.0,
    'Number of rows without duplicates': 209,
    'Number of rows with duplicates': 0,
    'Validity Score': 74.16,
    'Number of Invalid rows': 54,
    'Metrics': {'report': {0: {'precision': 0.8426966292134831,
       'recall': 0.8620689655172413,
       'f1-score': 0.8522727272727273,
       'support': 87},
      1: {'precision': 0.9,
       'recall': 0.8852459016393442,
       'f1-score': 0.8925619834710743,
       'support': 122},
      'accuracy': 0.8755980861244019,
      'macro avg': {'precision': 0.8713483146067416,
       'recall': 0.8736574335782927,
       'f1-score': 0.8724173553719008,
       'support': 209},
      'weighted avg': {'precision': 0.8761464437395838,
       'recall': 0.8755980861244019,
       'f1-score': 0.8757908576851595,
       'support': 209}},
     'Accuracy': 87.56,
     'Precision': 90.0,
     'Recall': 88.52,
     'F1': 89.26,
     'ROC_AUC': 87.37,
     'False Positive Rate': 13.79},
    'Drifting Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']},
   'Input Feature Details': {'Age': {'Number of missing values': 0,
     'Uniqueness Score': 20.1,
     'Number of datatype mismatches': 0,
     'Number of outliers': 0,
     'mean': 52.66,
     'median': 54.0,
     'std': 9.53,
     'min': 28,
     'max': 76,
     'iqr': 13.0,
     'type': 'int64',
     'KS-Test statistic': 0.09,
     'KS-Test p-value': 0.21,
     'Drift status given by KS-Test': False,
     'PSI statistic': 0.13,
     'Threshold used in PSI': 0.05,
     'Drift status given by PSI': True,
     'JS Distance statistic': 0.02,
     'Threshold used in JS Distance': 0.1,
     'Drift status given by JS Distance': False,
     'Final drift status': False},
    'Sex': {'Number of missing values': 0,
     'Uniqueness Score': 0.96,
     'Number of datatype mismatches': 0,
     'Number of outliers': 0,
     'mode': 'M',
     'value_counts': {'M': 177, 'F': 32},
     'type': 'object',
     'Chi Square statistic': 0.06,
     'Chi Square p-value': 0.81,
     'Drift status given by Chi Square': True,
     'PSI statistic': 0.05,
     'Threshold used in PSI': 0.2,
     'Drift status given by PSI': False,
     'JS Distance statistic': 0.08,
     'Threshold used in JS Distance': 0.2,
     'Drift status given by JS Distance': False,
     'Final drift status': False},
    'ChestPainType': {'Number of missing values': 16,
     'Uniqueness Score': 1.91,
     'Number of datatype mismatches': 0,
     'Number of outliers': 0,
     'mode': 'ASY',
     'value_counts': {'ASY': 100, 'NAP': 42, 'ATA': 36, 'TA': 15},
     'type': 'object',
     'Chi Square statistic': 7.5,
     'Chi Square p-value': 0.59,
     'Drift status given by Chi Square': True,
     'PSI statistic': 0.88,
     'Threshold used in PSI': 0.2,
     'Drift status given by PSI': True,
     'JS Distance statistic': 0.05,
     'Threshold used in JS Distance': 0.2,
     'Drift status given by JS Distance': False,
     'Final drift status': True},
    'RestingBP': {'Number of missing values': 16,
     'Uniqueness Score': 22.01,
     'Number of datatype mismatches': 0,
     'Number of outliers': 3,
     'mean': 129.8,
     'median': 130.0,
     'std': 18.35,
     'min': 80.0,
     'max': 192.0,
     'iqr': 20.0,
     'type': 'float64',
     'KS-Test statistic': 0.08,
     'KS-Test p-value': 0.28,
     'Drift status given by KS-Test': False,
     'PSI statistic': inf,
     'Threshold used in PSI': 0.05,
     'Drift status given by PSI': True,
     'JS Distance statistic': 0.01,
     'Threshold used in JS Distance': 0.1,
     'Drift status given by JS Distance': False,
     'Final drift status': False},
    'Cholesterol': {'Number of missing values': 38,
     'Uniqueness Score': 45.45,
     'Number of datatype mismatches': 0,
     'Number of outliers': 2,
     'mean': 186.86,
     'median': 219.0,
     'std': 113.14,
     'min': 0.0,
     'max': 564.0,
     'iqr': 108.0,
     'type': 'float64',
     'KS-Test statistic': 0.19,
     'KS-Test p-value': 0.0,
     'Drift status given by KS-Test': True,
     'PSI statistic': inf,
     'Threshold used in PSI': 0.05,
     'Drift status given by PSI': True,
     'JS Distance statistic': 0.02,
     'Threshold used in JS Distance': 0.1,
     'Drift status given by JS Distance': False,
     'Final drift status': True},
    'FastingBS': {'Number of missing values': 16,
     'Uniqueness Score': 0.96,
     'Number of datatype mismatches': 0,
     'Number of outliers': 0,
     'mean': 0.26,
     'median': 0.0,
     'std': 0.44,
     'min': 0.0,
     'max': 1.0,
     'iqr': 1.0,
     'type': 'float64',
     'KS-Test statistic': 0.09,
     'KS-Test p-value': 0.17,
     'Drift status given by KS-Test': False,
     'PSI statistic': 0.0,
     'Threshold used in PSI': 0.05,
     'Drift status given by PSI': False,
     'JS Distance statistic': 0.0,
     'Threshold used in JS Distance': 0.1,
     'Drift status given by JS Distance': False,
     'Final drift status': False},
    'RestingECG': {'Number of missing values': 16,
     'Uniqueness Score': 1.44,
     'Number of datatype mismatches': 0,
     'Number of outliers': 0,
     'mode': 'Normal',
     'value_counts': {'Normal': 118, 'ST': 38, 'LVH': 37},
     'type': 'object',
     'Chi Square statistic': 0.99,
     'Chi Square p-value': 0.91,
     'Drift status given by Chi Square': True,
     'PSI statistic': 0.87,
     'Threshold used in PSI': 0.2,
     'Drift status given by PSI': True,
     'JS Distance statistic': 0.02,
     'Threshold used in JS Distance': 0.2,
     'Drift status given by JS Distance': False,
     'Final drift status': True},
    'MaxHR': {'Number of missing values': 16,
     'Uniqueness Score': 38.76,
     'Number of datatype mismatches': 0,
     'Number of outliers': 1,
     'mean': 138.81,
     'median': 138.0,
     'std': 26.36,
     'min': 60.0,
     'max': 195.0,
     'iqr': 38.0,
     'type': 'float64',
     'KS-Test statistic': 0.14,
     'KS-Test p-value': 0.01,
     'Drift status given by KS-Test': True,
     'PSI statistic': 0.14,
     'Threshold used in PSI': 0.05,
     'Drift status given by PSI': True,
     'JS Distance statistic': 0.02,
     'Threshold used in JS Distance': 0.1,
     'Drift status given by JS Distance': False,
     'Final drift status': True},
    'ExerciseAngina': {'Number of missing values': 0,
     'Uniqueness Score': 1.44,
     'Number of datatype mismatches': 16,
     'Number of outliers': 0,
     'mode': 'N',
     'value_counts': {'N': 124, 'Y': 69, '1': 16},
     'type': 'object',
     'Chi Square statistic': 1.81,
     'Chi Square p-value': 0.41,
     'Drift status given by Chi Square': True,
     'PSI statistic': 0.89,
     'Threshold used in PSI': 0.2,
     'Drift status given by PSI': True,
     'JS Distance statistic': 0.17,
     'Threshold used in JS Distance': 0.2,
     'Drift status given by JS Distance': False,
     'Final drift status': True},
    'Oldpeak': {'Number of missing values': 0,
     'Uniqueness Score': 16.75,
     'Number of datatype mismatches': 0,
     'Number of outliers': 2,
     'mean': 0.79,
     'median': 0.5,
     'std': 0.97,
     'min': -1.1,
     'max': 4.0,
     'iqr': 1.5,
     'type': 'float64',
     'KS-Test statistic': 0.07,
     'KS-Test p-value': 0.38,
     'Drift status given by KS-Test': False,
     'PSI statistic': inf,
     'Threshold used in PSI': 0.05,
     'Drift status given by PSI': True,
     'JS Distance statistic': 0.01,
     'Threshold used in JS Distance': 0.1,
     'Drift status given by JS Distance': False,
     'Final drift status': False},
    'ST_Slope': {'Number of missing values': 0,
     'Uniqueness Score': 1.44,
     'Number of datatype mismatches': 0,
     'Number of outliers': 0,
     'mode': 'Up',
     'value_counts': {'Up': 97, 'Flat': 94, 'Down': 18},
     'type': 'object',
     'Chi Square statistic': 2.83,
     'Chi Square p-value': 0.59,
     'Drift status given by Chi Square': True,
     'PSI statistic': 0.02,
     'Threshold used in PSI': 0.2,
     'Drift status given by PSI': False,
     'JS Distance statistic': 0.05,
     'Threshold used in JS Distance': 0.2,
     'Drift status given by JS Distance': False,
     'Final drift status': False}},
   'Output Feature Details': {'mode': 1,
    'value_counts': {1: 120, 0: 89},
    'type': 'int64',
    'Chi Square statistic': 112.96,
    'Chi Square p-value': 0.0,
    'Drift status given by Chi Square': False,
    'PSI statistic': 0.0,
    'Threshold used in PSI': 0.2,
    'Drift status given by PSI': False,
    'JS Distance statistic': 0.01,
    'Threshold used in JS Distance': 0.2,
    'Drift status given by JS Distance': False,
    'Final drift status': False}}}}

In [9]:
results = new_results['Heart Disease Prediction']['07th Feb 2024.csv']

In [11]:
list(results.keys())

['Production Data Summary', 'Input Feature Details', 'Output Feature Details']

In [15]:
results['Production Data Summary']

{'Number of rows': 209,
 'Number of rows without NaN': 171,
 'Number of rows with Nan': 38,
 'Completeness Score': 81.82,
 'Uniqueness Score': 100.0,
 'Number of rows without duplicates': 209,
 'Number of rows with duplicates': 0,
 'Validity Score': 74.16,
 'Number of Invalid rows': 54,
 'Metrics': {'report': {0: {'precision': 0.8426966292134831,
    'recall': 0.8620689655172413,
    'f1-score': 0.8522727272727273,
    'support': 87},
   1: {'precision': 0.9,
    'recall': 0.8852459016393442,
    'f1-score': 0.8925619834710743,
    'support': 122},
   'accuracy': 0.8755980861244019,
   'macro avg': {'precision': 0.8713483146067416,
    'recall': 0.8736574335782927,
    'f1-score': 0.8724173553719008,
    'support': 209},
   'weighted avg': {'precision': 0.8761464437395838,
    'recall': 0.8755980861244019,
    'f1-score': 0.8757908576851595,
    'support': 209}},
  'Accuracy': 87.56,
  'Precision': 90.0,
  'Recall': 88.52,
  'F1': 89.26,
  'ROC_AUC': 87.37,
  'False Positive Rate': 13.79},
 'Drifting Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']}

In [13]:
results['Production Data Summary']['Metrics']

{'report': {0: {'precision': 0.8426966292134831,
   'recall': 0.8620689655172413,
   'f1-score': 0.8522727272727273,
   'support': 87},
  1: {'precision': 0.9,
   'recall': 0.8852459016393442,
   'f1-score': 0.8925619834710743,
   'support': 122},
  'accuracy': 0.8755980861244019,
  'macro avg': {'precision': 0.8713483146067416,
   'recall': 0.8736574335782927,
   'f1-score': 0.8724173553719008,
   'support': 209},
  'weighted avg': {'precision': 0.8761464437395838,
   'recall': 0.8755980861244019,
   'f1-score': 0.8757908576851595,
   'support': 209}},
 'Accuracy': 87.56,
 'Precision': 90.0,
 'Recall': 88.52,
 'F1': 89.26,
 'ROC_AUC': 87.37,
 'False Positive Rate': 13.79}

In [16]:
list(results['Input Feature Details'].keys())

['Age',
 'Sex',
 'ChestPainType',
 'RestingBP',
 'Cholesterol',
 'FastingBS',
 'RestingECG',
 'MaxHR',
 'ExerciseAngina',
 'Oldpeak',
 'ST_Slope']

In [17]:
results['Input Feature Details']['Age']

{'Number of missing values': 0,
 'Uniqueness Score': 20.1,
 'Number of datatype mismatches': 0,
 'Number of outliers': 0,
 'mean': 52.66,
 'median': 54.0,
 'std': 9.53,
 'min': 28,
 'max': 76,
 'iqr': 13.0,
 'type': 'int64',
 'KS-Test statistic': 0.09,
 'KS-Test p-value': 0.21,
 'Drift status given by KS-Test': False,
 'PSI statistic': 0.13,
 'Threshold used in PSI': 0.05,
 'Drift status given by PSI': True,
 'JS Distance statistic': 0.02,
 'Threshold used in JS Distance': 0.1,
 'Drift status given by JS Distance': False,
 'Final drift status': False}

In [18]:
results['Input Feature Details']['Sex']

{'Number of missing values': 0,
 'Uniqueness Score': 0.96,
 'Number of datatype mismatches': 0,
 'Number of outliers': 0,
 'mode': 'M',
 'value_counts': {'M': 177, 'F': 32},
 'type': 'object',
 'Chi Square statistic': 0.06,
 'Chi Square p-value': 0.81,
 'Drift status given by Chi Square': True,
 'PSI statistic': 0.05,
 'Threshold used in PSI': 0.2,
 'Drift status given by PSI': False,
 'JS Distance statistic': 0.08,
 'Threshold used in JS Distance': 0.2,
 'Drift status given by JS Distance': False,
 'Final drift status': False}

In [19]:
results['Output Feature Details']

{'mode': 1,
 'value_counts': {1: 120, 0: 89},
 'type': 'int64',
 'Chi Square statistic': 112.96,
 'Chi Square p-value': 0.0,
 'Drift status given by Chi Square': False,
 'PSI statistic': 0.0,
 'Threshold used in PSI': 0.2,
 'Drift status given by PSI': False,
 'JS Distance statistic': 0.01,
 'Threshold used in JS Distance': 0.2,
 'Drift status given by JS Distance': False,
 'Final drift status': False}

In [22]:
prod_summary = dict()

for i in list(results['Production Data Summary'].keys()):
    if i not in ['Metrics', 'Drifting Metrics']:
        prod_summary[i] = results['Production Data Summary'][i]

In [23]:
prod_summary

{'Number of rows': 209,
 'Number of rows without NaN': 171,
 'Number of rows with Nan': 38,
 'Completeness Score': 81.82,
 'Uniqueness Score': 100.0,
 'Number of rows without duplicates': 209,
 'Number of rows with duplicates': 0,
 'Validity Score': 74.16,
 'Number of Invalid rows': 54}

In [38]:
def separated_results(result_dict, model_name, prod_date, num_cols, cat_cols):
    
    results = result_dict[model_name][prod_date]
    data_drift, data_quality = dict(), dict()
    input_details = results['Input Feature Details']
    
    cols = num_cols + cat_cols
    # Performance Dict
    performance_dict = results['Production Data Summary']['Metrics']
    performance_dict['Drifting Performance Metrics'] = results['Production Data Summary']['Drifting Metrics']
    
    # Data Drift and Data Quality Dicts
    for i in cols:
        
        if i in num_cols:
            
            data_drift[i] = {'KS-Test statistic': input_details[i]['KS-Test statistic'],
                            'KS-Test p-value': input_details[i]['KS-Test p-value'],
                            'Drift status given by KS-Test': input_details[i]['Drift status given by KS-Test'],
                            'PSI statistic': input_details[i]['PSI statistic'],
                            'Threshold used in PSI': input_details[i]['Threshold used in PSI'],
                            'Drift status given by PSI': input_details[i]['Drift status given by PSI'],
                            'JS Distance statistic': input_details[i]['JS Distance statistic'],
                            'Threshold used in JS Distance': input_details[i]['Threshold used in JS Distance'],
                            'Drift status given by JS Distance': input_details[i]['Drift status given by JS Distance'],
                            'Final drift status by voting': input_details[i]['Final drift status']}
            
           # Number of duplicates, completeness score, number of invalid points, validity score
        
            data_quality[i] = {'Number of missing values': input_details[i]['Number of missing values'],
                          'Uniqueness Score': input_details[i]['Uniqueness Score'],
                          'Number of datatype mismatches': input_details[i]['Number of datatype mismatches'],
                          'Number of outliers': input_details[i]['Number of outliers'],
                          'Mean': input_details[i]['mean'],
                          'Datatype': input_details[i]['type'],
                          'Median': input_details[i]['median'],
                          'Standard Deviation': input_details[i]['std'],
                          'Min value': input_details[i]['min'],
                          'Max value': input_details[i]['max'],
                          'Inter quartile Range': input_details[i]['iqr']
                          }
            
        if i in cat_cols:
            
            data_drift[i] = {'Chi Square statistic': input_details[i]['Chi Square statistic'],
                            'Chi Square p-value': input_details[i]['Chi Square p-value'],
                            'Drift status given by Chi Square': input_details[i]['Drift status given by Chi Square'],
                            'PSI statistic': input_details[i]['PSI statistic'],
                            'Threshold used in PSI': input_details[i]['Threshold used in PSI'],
                            'Drift status given by PSI': input_details[i]['Drift status given by PSI'],
                            'JS Distance statistic': input_details[i]['JS Distance statistic'],
                            'Threshold used in JS Distance': input_details[i]['Threshold used in JS Distance'],
                            'Drift status given by JS Distance': input_details[i]['Drift status given by JS Distance'],
                            'Final drift status by voting': input_details[i]['Final drift status']}
            
            data_quality[i] = {'Number of missing values': input_details[i]['Number of missing values'],
                              'Uniqueness Score': input_details[i]['Uniqueness Score'],
                              'Number of datatype mismatches': input_details[i]['Number of datatype mismatches'],
                              'Number of outliers': input_details[i]['Number of outliers'],
                               'Mode': input_details[i]['mode'],
                              'Count of unique categories': input_details[i]['value_counts'],
                               'Datatype': input_details[i]['type']
                              }
        
        data_drift['Drifting Features in Data'] = [i for i in cols if input_details[i]['Final drift status'] == True]
    
    # Prediction Dict
    prediction_drift = results['Output Feature Details']
    
    # Production Data Details
    prod_summary = dict()

    for i in list(results['Production Data Summary'].keys()):
        if i not in ['Metrics', 'Drifting Metrics']:
            prod_summary[i] = results['Production Data Summary'][i]
    
    return prod_summary, performance_dict, data_drift, data_quality, prediction_drift

In [39]:
from utils import determine_dtype_ft

In [40]:
cat_ft, num_ft = determine_dtype_ft(baseline.drop("target", axis=1))

In [41]:
cat_ft, num_ft

(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'],
 ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak'])

In [42]:
prod_summary, performance_dict, data_drift, data_quality, prediction_drift = separated_results(new_results,
                                                                                            "Heart Disease Prediction",
                                                                                              "07th Feb 2024.csv",
                                                                                             num_ft, cat_ft)

In [43]:
prod_summary

{'Number of rows': 209,
 'Number of rows without NaN': 171,
 'Number of rows with Nan': 38,
 'Completeness Score': 81.82,
 'Uniqueness Score': 100.0,
 'Number of rows without duplicates': 209,
 'Number of rows with duplicates': 0,
 'Validity Score': 74.16,
 'Number of Invalid rows': 54}

In [44]:
performance_dict

{'report': {0: {'precision': 0.8426966292134831,
   'recall': 0.8620689655172413,
   'f1-score': 0.8522727272727273,
   'support': 87},
  1: {'precision': 0.9,
   'recall': 0.8852459016393442,
   'f1-score': 0.8925619834710743,
   'support': 122},
  'accuracy': 0.8755980861244019,
  'macro avg': {'precision': 0.8713483146067416,
   'recall': 0.8736574335782927,
   'f1-score': 0.8724173553719008,
   'support': 209},
  'weighted avg': {'precision': 0.8761464437395838,
   'recall': 0.8755980861244019,
   'f1-score': 0.8757908576851595,
   'support': 209}},
 'Accuracy': 87.56,
 'Precision': 90.0,
 'Recall': 88.52,
 'F1': 89.26,
 'ROC_AUC': 87.37,
 'False Positive Rate': 13.79,
 'Drifting Performance Metrics': ['Accuracy',
  'ROC_AUC',
  'False Positive Rate']}

In [45]:
data_drift

{'Age': {'KS-Test statistic': 0.09,
  'KS-Test p-value': 0.21,
  'Drift status given by KS-Test': False,
  'PSI statistic': 0.13,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.02,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'Drifting Features in Data': ['Cholesterol',
  'MaxHR',
  'ChestPainType',
  'RestingECG',
  'ExerciseAngina'],
 'RestingBP': {'KS-Test statistic': 0.08,
  'KS-Test p-value': 0.28,
  'Drift status given by KS-Test': False,
  'PSI statistic': inf,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.01,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'Cholesterol': {'KS-Test statistic': 0.19,
  'KS-Test p-value': 0.0,
  'Drift status given by KS-Test': True,
  'PSI statistic': inf,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.02,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'FastingBS': {'KS-Test statistic': 0.09,
  'KS-Test p-value': 0.17,
  'Drift status given by KS-Test': False,
  'PSI statistic': 0.0,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': False,
  'JS Distance statistic': 0.0,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'MaxHR': {'KS-Test statistic': 0.14,
  'KS-Test p-value': 0.01,
  'Drift status given by KS-Test': True,
  'PSI statistic': 0.14,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.02,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'Oldpeak': {'KS-Test statistic': 0.07,
  'KS-Test p-value': 0.38,
  'Drift status given by KS-Test': False,
  'PSI statistic': inf,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.01,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'Sex': {'Chi Square statistic': 0.06,
  'Chi Square p-value': 0.81,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.05,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': False,
  'JS Distance statistic': 0.08,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'ChestPainType': {'Chi Square statistic': 7.5,
  'Chi Square p-value': 0.59,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.88,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.05,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'RestingECG': {'Chi Square statistic': 0.99,
  'Chi Square p-value': 0.91,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.87,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.02,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'ExerciseAngina': {'Chi Square statistic': 1.81,
  'Chi Square p-value': 0.41,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.89,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.17,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'ST_Slope': {'Chi Square statistic': 2.83,
  'Chi Square p-value': 0.59,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.02,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': False,
  'JS Distance statistic': 0.05,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False}}

In [46]:
prediction_drift

{'mode': 1,
 'value_counts': {1: 120, 0: 89},
 'type': 'int64',
 'Chi Square statistic': 112.96,
 'Chi Square p-value': 0.0,
 'Drift status given by Chi Square': False,
 'PSI statistic': 0.0,
 'Threshold used in PSI': 0.2,
 'Drift status given by PSI': False,
 'JS Distance statistic': 0.01,
 'Threshold used in JS Distance': 0.2,
 'Drift status given by JS Distance': False,
 'Final drift status': False}

In [47]:
data_quality

{'Age': {'Number of missing values': 0,
  'Uniqueness Score': 20.1,
  'Number of datatype mismatches': 0,
  'Number of outliers': 0,
  'Mean': 52.66,
  'Datatype': 'int64',
  'Median': 54.0,
  'Standard Deviation': 9.53,
  'Min value': 28,
  'Max value': 76,
  'Inter quartile Range': 13.0},
 'RestingBP': {'Number of missing values': 16,
  'Uniqueness Score': 22.01,
  'Number of datatype mismatches': 0,
  'Number of outliers': 3,
  'Mean': 129.8,
  'Datatype': 'float64',
  'Median': 130.0,
  'Standard Deviation': 18.35,
  'Min value': 80.0,
  'Max value': 192.0,
  'Inter quartile Range': 20.0},
 'Cholesterol': {'Number of missing values': 38,
  'Uniqueness Score': 45.45,
  'Number of datatype mismatches': 0,
  'Number of outliers': 2,
  'Mean': 186.86,
  'Datatype': 'float64',
  'Median': 219.0,
  'Standard Deviation': 113.14,
  'Min value': 0.0,
  'Max value': 564.0,
  'Inter quartile Range': 108.0},
 'FastingBS': {'Number of missing values': 16,
  'Uniqueness Score': 0.96,
  'Number of datatype mismatches': 0,
  'Number of outliers': 0,
  'Mean': 0.26,
  'Datatype': 'float64',
  'Median': 0.0,
  'Standard Deviation': 0.44,
  'Min value': 0.0,
  'Max value': 1.0,
  'Inter quartile Range': 1.0},
 'MaxHR': {'Number of missing values': 16,
  'Uniqueness Score': 38.76,
  'Number of datatype mismatches': 0,
  'Number of outliers': 1,
  'Mean': 138.81,
  'Datatype': 'float64',
  'Median': 138.0,
  'Standard Deviation': 26.36,
  'Min value': 60.0,
  'Max value': 195.0,
  'Inter quartile Range': 38.0},
 'Oldpeak': {'Number of missing values': 0,
  'Uniqueness Score': 16.75,
  'Number of datatype mismatches': 0,
  'Number of outliers': 2,
  'Mean': 0.79,
  'Datatype': 'float64',
  'Median': 0.5,
  'Standard Deviation': 0.97,
  'Min value': -1.1,
  'Max value': 4.0,
  'Inter quartile Range': 1.5},
 'Sex': {'Number of missing values': 0,
  'Uniqueness Score': 0.96,
  'Number of datatype mismatches': 0,
  'Number of outliers': 0,
  'Mode': 'M',
  'Count of unique categories': {'M': 177, 'F': 32},
  'Datatype': 'object'},
 'ChestPainType': {'Number of missing values': 16,
  'Uniqueness Score': 1.91,
  'Number of datatype mismatches': 0,
  'Number of outliers': 0,
  'Mode': 'ASY',
  'Count of unique categories': {'ASY': 100, 'NAP': 42, 'ATA': 36, 'TA': 15},
  'Datatype': 'object'},
 'RestingECG': {'Number of missing values': 16,
  'Uniqueness Score': 1.44,
  'Number of datatype mismatches': 0,
  'Number of outliers': 0,
  'Mode': 'Normal',
  'Count of unique categories': {'Normal': 118, 'ST': 38, 'LVH': 37},
  'Datatype': 'object'},
 'ExerciseAngina': {'Number of missing values': 0,
  'Uniqueness Score': 1.44,
  'Number of datatype mismatches': 16,
  'Number of outliers': 0,
  'Mode': 'N',
  'Count of unique categories': {'N': 124, 'Y': 69, '1': 16},
  'Datatype': 'object'},
 'ST_Slope': {'Number of missing values': 0,
  'Uniqueness Score': 1.44,
  'Number of datatype mismatches': 0,
  'Number of outliers': 0,
  'Mode': 'Up',
  'Count of unique categories': {'Up': 97, 'Flat': 94, 'Down': 18},
  'Datatype': 'object'}}

### Structuring Prompts

In [50]:
def get_prompt(prompt, production_date, prod_summary, performance_drift, data_drift, data_quality, prediction_drift):
    
    message = f"""Information about current production run on {production_date}:
    An overall summary of the data we got on this production run is:
    {prod_summary}
    
    On performance analyses, we get the following results:
    
    For Performance Drift Analysis results are: {performance_drift}
    
    For Data Drift Analysis results are: {data_drift}
    
    For Prediction Drift Analysis results are: {prediction_drift}
    
    For Data Quality Analysis results are: {data_quality}
    
    Prompt: {prompt}
    
    Be very brief and informative. Also, make sure to follow the instructions provided by the system.
    """
    return message

In [51]:
print(get_prompt("I need to know about the data!", "00/00/0000", prod_summary, performance_dict, data_drift, data_quality, 
                 prediction_drift))

Information about current production run on 00/00/0000:
    An overall summary of the data we got on this production run is:
    {'Number of rows': 209, 'Number of rows without NaN': 171, 'Number of rows with Nan': 38, 'Completeness Score': 81.82, 'Uniqueness Score': 100.0, 'Number of rows without duplicates': 209, 'Number of rows with duplicates': 0, 'Validity Score': 74.16, 'Number of Invalid rows': 54}

    On performance analyses, we get the following results:

    For Performance Drift Analysis results are: {'report': {0: {'precision': 0.8426966292134831, 'recall': 0.8620689655172413, 'f1-score': 0.8522727272727273, 'support': 87}, 1: {'precision': 0.9, 'recall': 0.8852459016393442, 'f1-score': 0.8925619834710743, 'support': 122}, 'accuracy': 0.8755980861244019, 'macro avg': {'precision': 0.8713483146067416, 'recall': 0.8736574335782927, 'f1-score': 0.8724173553719008, 'support': 209}, 'weighted avg': {'precision': 0.8761464437395838, 'recall': 0.8755980861244019, 'f1-score': 0.8757908576851595, 'support': 209}}, 'Accuracy': 87.56, 'Precision': 90.0, 'Recall': 88.52, 'F1': 89.26, 'ROC_AUC': 87.37, 'False Positive Rate': 13.79, 'Drifting Performance Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']}

    For Data Drift Analysis results are: {'Age': {'KS-Test statistic': 0.09, 'KS-Test p-value': 0.21, 'Drift status given by KS-Test': False, 'PSI statistic': 0.13, 'Threshold used in PSI': 0.05, 'Drift status given by PSI': True, 'JS Distance statistic': 0.02, 'Threshold used in JS Distance': 0.1, 'Drift status given by JS Distance': False, 'Final drift status by voting': False}, 'Drifting Features in Data': ['Cholesterol', 'MaxHR', 'ChestPainType', 'RestingECG', 'ExerciseAngina'], 'RestingBP': {'KS-Test statistic': 0.08, 'KS-Test p-value': 0.28, 'Drift status given by KS-Test': False, 'PSI statistic': inf, 'Threshold used in PSI': 0.05, 'Drift status given by PSI': True, 'JS Distance statistic': 0.01, 'Threshold used in JS Distance': 0.1, 'Drift status given by JS Distance': False, 'Final drift status by voting': False}, 'Cholesterol': {'KS-Test statistic': 0.19, 'KS-Test p-value': 0.0, 'Drift status given by KS-Test': True, 'PSI statistic': inf, 'Threshold used in PSI': 0.05, 'Drift status given by PSI': True, 'JS Distance statistic': 0.02, 'Threshold used in JS Distance': 0.1, 'Drift status given by JS Distance': False, 'Final drift status by voting': True}, 'FastingBS': {'KS-Test statistic': 0.09, 'KS-Test p-value': 0.17, 'Drift status given by KS-Test': False, 'PSI statistic': 0.0, 'Threshold used in PSI': 0.05, 'Drift status given by PSI': False, 'JS Distance statistic': 0.0, 'Threshold used in JS Distance': 0.1, 'Drift status given by JS Distance': False, 'Final drift status by voting': False}, 'MaxHR': {'KS-Test statistic': 0.14, 'KS-Test p-value': 0.01, 'Drift status given by KS-Test': True, 'PSI statistic': 0.14, 'Threshold used in PSI': 0.05, 'Drift status given by PSI': True, 'JS Distance statistic': 0.02, 'Threshold used in JS Distance': 0.1, 'Drift status given by JS Distance': False, 'Final drift status by voting': True}, 'Oldpeak': {'KS-Test statistic': 0.07, 'KS-Test p-value': 0.38, 'Drift status given by KS-Test': False, 'PSI statistic': inf, 'Threshold used in PSI': 0.05, 'Drift status given by PSI': True, 'JS Distance statistic': 0.01, 'Threshold used in JS Distance': 0.1, 'Drift status given by JS Distance': False, 'Final drift status by voting': False}, 'Sex': {'Chi Square statistic': 0.06, 'Chi Square p-value': 0.81, 'Drift status given by Chi Square': True, 'PSI statistic': 0.05, 'Threshold used in PSI': 0.2, 'Drift status given by PSI': False, 'JS Distance statistic': 0.08, 'Threshold used in JS Distance': 0.2, 'Drift status given by JS Distance': False, 'Final drift status by voting': False}, 'ChestPainType': {'Chi Square statistic': 7.5, 'Chi Square p-value': 0.59, 'Drift status given by Chi Square': True, 'PSI statistic': 0.88, 'Threshold used in PSI': 0.2, 'Drift status given by PSI': True, 'JS Distance statistic': 0.05, 'Threshold used in JS Distance': 0.2, 'Drift status given by JS Distance': False, 'Final drift status by voting': True}, 'RestingECG': {'Chi Square statistic': 0.99, 'Chi Square p-value': 0.91, 'Drift status given by Chi Square': True, 'PSI statistic': 0.87, 'Threshold used in PSI': 0.2, 'Drift status given by PSI': True, 'JS Distance statistic': 0.02, 'Threshold used in JS Distance': 0.2, 'Drift status given by JS Distance': False, 'Final drift status by voting': True}, 'ExerciseAngina': {'Chi Square statistic': 1.81, 'Chi Square p-value': 0.41, 'Drift status given by Chi Square': True, 'PSI statistic': 0.89, 'Threshold used in PSI': 0.2, 'Drift status given by PSI': True, 'JS Distance statistic': 0.17, 'Threshold used in JS Distance': 0.2, 'Drift status given by JS Distance': False, 'Final drift status by voting': True}, 'ST_Slope': {'Chi Square statistic': 2.83, 'Chi Square p-value': 0.59, 'Drift status given by Chi Square': True, 'PSI statistic': 0.02, 'Threshold used in PSI': 0.2, 'Drift status given by PSI': False, 'JS Distance statistic': 0.05, 'Threshold used in JS Distance': 0.2, 'Drift status given by JS Distance': False, 'Final drift status by voting': False}}

    For Prediction Drift Analysis results are: {'mode': 1, 'value_counts': {1: 120, 0: 89}, 'type': 'int64', 'Chi Square statistic': 112.96, 'Chi Square p-value': 0.0, 'Drift status given by Chi Square': False, 'PSI statistic': 0.0, 'Threshold used in PSI': 0.2, 'Drift status given by PSI': False, 'JS Distance statistic': 0.01, 'Threshold used in JS Distance': 0.2, 'Drift status given by JS Distance': False, 'Final drift status': False}

    For Data Quality Analysis results are: {'Age': {'Number of missing values': 0, 'Uniqueness Score': 20.1, 'Number of datatype mismatches': 0, 'Number of outliers': 0, 'Mean': 52.66, 'Datatype': 'int64', 'Median': 54.0, 'Standard Deviation': 9.53, 'Min value': 28, 'Max value': 76, 'Inter quartile Range': 13.0}, 'RestingBP': {'Number of missing values': 16, 'Uniqueness Score': 22.01, 'Number of datatype mismatches': 0, 'Number of outliers': 3, 'Mean': 129.8, 'Datatype': 'float64', 'Median': 130.0, 'Standard Deviation': 18.35, 'Min value': 80.0, 'Max value': 192.0, 'Inter quartile Range': 20.0}, 'Cholesterol': {'Number of missing values': 38, 'Uniqueness Score': 45.45, 'Number of datatype mismatches': 0, 'Number of outliers': 2, 'Mean': 186.86, 'Datatype': 'float64', 'Median': 219.0, 'Standard Deviation': 113.14, 'Min value': 0.0, 'Max value': 564.0, 'Inter quartile Range': 108.0}, 'FastingBS': {'Number of missing values': 16, 'Uniqueness Score': 0.96, 'Number of datatype mismatches': 0, 'Number of outliers': 0, 'Mean': 0.26, 'Datatype': 'float64', 'Median': 0.0, 'Standard Deviation': 0.44, 'Min value': 0.0, 'Max value': 1.0, 'Inter quartile Range': 1.0}, 'MaxHR': {'Number of missing values': 16, 'Uniqueness Score': 38.76, 'Number of datatype mismatches': 0, 'Number of outliers': 1, 'Mean': 138.81, 'Datatype': 'float64', 'Median': 138.0, 'Standard Deviation': 26.36, 'Min value': 60.0, 'Max value': 195.0, 'Inter quartile Range': 38.0}, 'Oldpeak': {'Number of missing values': 0, 'Uniqueness Score': 16.75, 'Number of datatype mismatches': 0, 'Number of outliers': 2, 'Mean': 0.79, 'Datatype': 'float64', 'Median': 0.5, 'Standard Deviation': 0.97, 'Min value': -1.1, 'Max value': 4.0, 'Inter quartile Range': 1.5}, 'Sex': {'Number of missing values': 0, 'Uniqueness Score': 0.96, 'Number of datatype mismatches': 0, 'Number of outliers': 0, 'Mode': 'M', 'Count of unique categories': {'M': 177, 'F': 32}, 'Datatype': 'object'}, 'ChestPainType': {'Number of missing values': 16, 'Uniqueness Score': 1.91, 'Number of datatype mismatches': 0, 'Number of outliers': 0, 'Mode': 'ASY', 'Count of unique categories': {'ASY': 100, 'NAP': 42, 'ATA': 36, 'TA': 15}, 'Datatype': 'object'}, 'RestingECG': {'Number of missing values': 16, 'Uniqueness Score': 1.44, 'Number of datatype mismatches': 0, 'Number of outliers': 0, 'Mode': 'Normal', 'Count of unique categories': {'Normal': 118, 'ST': 38, 'LVH': 37}, 'Datatype': 'object'}, 'ExerciseAngina': {'Number of missing values': 0, 'Uniqueness Score': 1.44, 'Number of datatype mismatches': 16, 'Number of outliers': 0, 'Mode': 'N', 'Count of unique categories': {'N': 124, 'Y': 69, '1': 16}, 'Datatype': 'object'}, 'ST_Slope': {'Number of missing values': 0, 'Uniqueness Score': 1.44, 'Number of datatype mismatches': 0, 'Number of outliers': 0, 'Mode': 'Up', 'Count of unique categories': {'Up': 97, 'Flat': 94, 'Down': 18}, 'Datatype': 'object'}}

    Prompt: I need to know about the data!

    Be very brief and informative. Also, make sure to follow the instructions provided by the system.

In [52]:
dict1 = {'a': 1, 'b': 4, 1: 4}
dict2 = {'c': 6, 7:8}
dict3 = {4:3, 9:10}
dict2.update(dict3)

In [53]:
dict2

{'c': 6, 7: 8, 4: 3, 9: 10}

In [55]:
dict2.update({9:{10:12}})

In [56]:
dict2

{'c': 6, 7: 8, 4: 3, 9: {10: 12}}

In [57]:
dict2.update({9:{11:13}})

In [58]:
dict2

{'c': 6, 7: 8, 4: 3, 9: {11: 13}}

In [59]:
baseline.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
3,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
4,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0

In [61]:
ground_truths.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
0,63,F,ATA,140,195,0,Normal,179,N,0.0,Up,0
1,53,M,NAP,145,518,0,Normal,130,N,0.0,Flat,1
2,65,M,ASY,160,0,1,ST,122,N,1.2,Flat,1
3,56,M,ASY,130,0,0,LVH,122,Y,1.0,Flat,1
4,54,M,ATA,108,309,0,Normal,156,N,0.0,Up,0

In [62]:
production_run.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target,probs
0,63,F,ATA,140.0,195.0,0.0,Normal,179.0,N,0.0,Up,0,1.0
1,53,M,NAP,145.0,518.0,0.0,Normal,130.0,N,0.0,Flat,1,0.6
2,65,M,ASY,160.0,0.0,1.0,ST,122.0,N,1.2,Flat,1,1.0
3,56,M,ASY,130.0,0.0,0.0,LVH,122.0,Y,1.0,Flat,1,1.0
4,54,M,ATA,108.0,309.0,0.0,Normal,156.0,N,0.0,Up,0,1.0

In [75]:
filtered_gt = ground_truths[ground_truths['ChestPainType'] == 'ATA']

In [76]:
filtered_pr = production_run[production_run['ChestPainType'] == 'ATA']

In [77]:
filtered_gt

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
0,63,F,ATA,140,195,0,Normal,179,N,0.0,Up,0
4,54,M,ATA,108,309,0,Normal,156,N,0.0,Up,0
13,56,M,ATA,120,236,0,Normal,178,N,0.8,Up,0
26,48,M,ATA,130,245,0,Normal,160,N,0.0,Up,0
28,44,M,ATA,130,219,0,LVH,188,N,0.0,Up,0
29,32,M,ATA,110,225,0,Normal,184,N,0.0,Up,0
39,57,M,ATA,140,265,0,ST,145,Y,1.0,Flat,1
41,44,M,ATA,150,288,0,Normal,150,Y,3.0,Flat,1
50,54,M,ATA,192,283,0,LVH,195,N,0.0,Up,1
51,34,M,ATA,150,214,0,ST,168,N,0.0,Up,0
55,61,F,ATA,140,298,1,Normal,120,Y,0.0,Up,0
56,59,F,ATA,130,188,0,Normal,124,N,1.0,Flat,0
62,43,F,ATA,120,215,0,ST,175,N,0.0,Up,0
64,28,M,ATA,130,132,0,LVH,185,N,0.0,Up,0
73,53,M,ATA,120,0,0,Normal,95,N,0.0,Flat,1
77,60,M,ATA,160,267,1,ST,157,N,0.5,Flat,1
83,49,M,ATA,100,253,0,Normal,174,N,0.0,Up,0
86,56,M,ATA,126,166,0,ST,140,N,0.0,Up,0
93,46,M,ATA,140,275,0,Normal,165,Y,0.0,Up,0
94,39,M,ATA,120,200,0,Normal,160,Y,1.0,Flat,0
95,55,M,ATA,140,196,0,Normal,150,N,0.0,Up,0
100,39,M,ATA,120,241,0,ST,146,N,2.0,Up,0
124,56,M,ATA,130,221,0,LVH,163,N,0.0,Up,0
125,43,M,ATA,142,207,0,Normal,138,N,0.0,Up,0
126,63,F,ATA,132,0,0,Normal,130,N,0.1,Up,0
130,52,M,ATA,140,100,0,Normal,138,Y,0.0,Up,0
135,63,M,ATA,136,165,0,ST,133,N,0.2,Up,0
138,37,F,ATA,120,260,0,Normal,130,N,0.0,Up,0
150,44,M,ATA,120,263,0,Normal,173,N,0.0,Up,0
153,50,F,ATA,120,244,0,Normal,162,N,1.1,Up,0
160,39,M,ATA,190,241,0,Normal,106,N,0.0,Up,0
169,59,M,ATA,140,221,0,Normal,164,Y,0.0,Up,0
174,54,M,ATA,160,305,0,Normal,175,N,0.0,Up,0
182,49,M,ATA,130,266,0,Normal,171,N,0.6,Up,0
196,51,M,ATA,125,188,0,Normal,145,N,0.0,Up,0
197,51,F,ATA,160,194,0,Normal,170,N,0.0,Up,0
201,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
204,54,M,ATA,120,238,0,Normal,154,N,0.0,Up,0

In [78]:
filtered_pr

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target,probs
0,63,F,ATA,140.0,195.0,0.0,Normal,179.0,N,0.0,Up,0,1.0
4,54,M,ATA,108.0,309.0,0.0,Normal,156.0,N,0.0,Up,0,1.0
13,56,M,ATA,120.0,236.0,0.0,Normal,178.0,N,0.8,Up,0,1.0
26,48,M,ATA,130.0,245.0,0.0,Normal,160.0,N,0.0,Up,0,1.0
28,44,M,ATA,130.0,219.0,0.0,LVH,188.0,N,0.0,Up,0,0.8
29,32,M,ATA,110.0,225.0,0.0,Normal,184.0,N,0.0,Up,0,1.0
50,54,M,ATA,192.0,283.0,0.0,LVH,195.0,N,0.0,Up,0,0.8
51,34,M,ATA,150.0,214.0,0.0,ST,168.0,N,0.0,Up,0,1.0
55,61,F,ATA,140.0,298.0,1.0,Normal,120.0,Y,0.0,Up,0,1.0
56,59,F,ATA,130.0,188.0,0.0,Normal,124.0,N,1.0,Flat,0,1.0
62,43,F,ATA,120.0,215.0,0.0,ST,175.0,1,0.0,Up,0,1.0
64,28,M,ATA,130.0,132.0,0.0,LVH,185.0,1,0.0,Up,0,0.8
73,53,M,ATA,120.0,0.0,0.0,Normal,95.0,N,0.0,Flat,0,0.8
77,60,M,ATA,160.0,267.0,1.0,ST,157.0,N,0.5,Flat,1,0.6
83,49,M,ATA,100.0,253.0,0.0,Normal,174.0,N,0.0,Up,0,1.0
86,56,M,ATA,126.0,166.0,0.0,ST,140.0,N,0.0,Up,0,1.0
93,46,M,ATA,140.0,NaN,0.0,Normal,165.0,Y,0.0,Up,0,1.0
94,39,M,ATA,120.0,NaN,0.0,Normal,160.0,Y,1.0,Flat,0,0.6
95,55,M,ATA,140.0,NaN,0.0,Normal,150.0,N,0.0,Up,0,1.0
100,39,M,ATA,120.0,NaN,0.0,ST,146.0,N,2.0,Up,0,1.0
124,56,M,ATA,130.0,221.0,0.0,LVH,163.0,N,0.0,Up,0,0.8
125,43,M,ATA,142.0,207.0,0.0,Normal,138.0,N,0.0,Up,0,1.0
126,63,F,ATA,132.0,0.0,0.0,Normal,130.0,N,0.1,Up,0,1.0
130,52,M,ATA,140.0,100.0,0.0,Normal,138.0,Y,0.0,Up,0,1.0
135,63,M,ATA,136.0,165.0,0.0,ST,133.0,N,0.2,Up,0,0.8
138,37,F,ATA,120.0,260.0,0.0,Normal,130.0,N,0.0,Up,0,1.0
150,44,M,ATA,120.0,263.0,0.0,Normal,173.0,N,0.0,Up,0,1.0
153,50,F,ATA,120.0,244.0,0.0,Normal,162.0,N,1.1,Up,0,1.0
160,39,M,ATA,190.0,241.0,0.0,Normal,106.0,N,0.0,Up,0,1.0
169,59,M,ATA,140.0,221.0,0.0,Normal,164.0,Y,0.0,Up,0,1.0
174,54,M,ATA,160.0,305.0,0.0,Normal,175.0,N,0.0,Up,0,1.0
182,49,M,ATA,130.0,266.0,0.0,Normal,171.0,N,0.6,Up,0,1.0
196,51,M,ATA,125.0,188.0,0.0,Normal,145.0,N,0.0,Up,0,1.0
197,51,F,ATA,160.0,194.0,0.0,Normal,170.0,N,0.0,Up,0,1.0
201,57,F,ATA,130.0,236.0,0.0,LVH,174.0,N,0.0,Flat,0,1.0
204,54,M,ATA,120.0,238.0,0.0,Normal,154.0,N,0.0,Up,0,1.0

In [70]:
random_indices = [36, 21, 48]
another = [26, 28, 36, 48]

In [71]:
ground_truths.iloc[random_indices]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
36,52,M,ASY,140,266,0,Normal,134,Y,2.0,Flat,1
21,48,F,ASY,150,227,0,Normal,130,Y,1.0,Flat,0
48,53,M,ASY,120,0,1,Normal,120,N,0.0,Flat,1

In [72]:
ground_truths.iloc[another]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
26,48,M,ATA,130,245,0,Normal,160,N,0.0,Up,0
28,44,M,ATA,130,219,0,LVH,188,N,0.0,Up,0
36,52,M,ASY,140,266,0,Normal,134,Y,2.0,Flat,1
48,53,M,ASY,120,0,1,Normal,120,N,0.0,Flat,1

In [82]:
to_analyse = set(filtered_gt.index).intersection(set(filtered_pr.index))

In [84]:
extra = list(set(filtered_gt.index) - to_analyse) + list(set(filtered_pt.index) - to_analyse)

{0,
 4,
 13,
 26,
 28,
 29,
 39,
 41,
 50,
 51,
 55,
 56,
 62,
 64,
 73,
 77,
 83,
 86,
 93,
 94,
 95,
 100,
 124,
 125,
 126,
 130,
 135,
 138,
 150,
 153,
 160,
 169,
 174,
 182,
 196,
 197,
 201,
 204}

In [85]:
data_drift

{'Age': {'KS-Test statistic': 0.09,
  'KS-Test p-value': 0.21,
  'Drift status given by KS-Test': False,
  'PSI statistic': 0.13,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.02,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'Drifting Features in Data': ['Cholesterol',
  'MaxHR',
  'ChestPainType',
  'RestingECG',
  'ExerciseAngina'],
 'RestingBP': {'KS-Test statistic': 0.08,
  'KS-Test p-value': 0.28,
  'Drift status given by KS-Test': False,
  'PSI statistic': inf,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.01,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'Cholesterol': {'KS-Test statistic': 0.19,
  'KS-Test p-value': 0.0,
  'Drift status given by KS-Test': True,
  'PSI statistic': inf,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.02,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'FastingBS': {'KS-Test statistic': 0.09,
  'KS-Test p-value': 0.17,
  'Drift status given by KS-Test': False,
  'PSI statistic': 0.0,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': False,
  'JS Distance statistic': 0.0,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'MaxHR': {'KS-Test statistic': 0.14,
  'KS-Test p-value': 0.01,
  'Drift status given by KS-Test': True,
  'PSI statistic': 0.14,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.02,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'Oldpeak': {'KS-Test statistic': 0.07,
  'KS-Test p-value': 0.38,
  'Drift status given by KS-Test': False,
  'PSI statistic': inf,
  'Threshold used in PSI': 0.05,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.01,
  'Threshold used in JS Distance': 0.1,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'Sex': {'Chi Square statistic': 0.06,
  'Chi Square p-value': 0.81,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.05,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': False,
  'JS Distance statistic': 0.08,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False},
 'ChestPainType': {'Chi Square statistic': 7.5,
  'Chi Square p-value': 0.59,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.88,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.05,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'RestingECG': {'Chi Square statistic': 0.99,
  'Chi Square p-value': 0.91,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.87,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.02,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'ExerciseAngina': {'Chi Square statistic': 1.81,
  'Chi Square p-value': 0.41,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.89,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': True,
  'JS Distance statistic': 0.17,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': True},
 'ST_Slope': {'Chi Square statistic': 2.83,
  'Chi Square p-value': 0.59,
  'Drift status given by Chi Square': True,
  'PSI statistic': 0.02,
  'Threshold used in PSI': 0.2,
  'Drift status given by PSI': False,
  'JS Distance statistic': 0.05,
  'Threshold used in JS Distance': 0.2,
  'Drift status given by JS Distance': False,
  'Final drift status by voting': False}}

In [90]:
from utils import ks_test, chi_test, psi, psi_num, js_test, js_num

In [86]:
baseline_data = baseline.drop('target', axis=1)
production_data = production_run.drop('target', axis=1)

In [91]:
categorical_ft, numerical_ft = determine_dtype_ft(baseline_data)

In [92]:
ks_results , ks_figs = ks_test(baseline_data,production_data,num_ft = numerical_ft)

In [93]:
chi_results, chi_figs = chi_test(baseline_data, production_data, categorical_ft=categorical_ft)

In [94]:
psi_results, psi_figs = psi(baseline_data, production_data, categorical_ft=categorical_ft)
js_results, js_figs = js_test(baseline_data, production_data, features=categorical_ft)
psi_num_results, psi_num_figs = psi_num(baseline_data, production_data, num_ft = numerical_ft)
js_num_results, js_num_figs = js_num(baseline_data, production_data ,num_ft = numerical_ft)

C:\Users\Akshat Mittu\AppData\Roaming\Python\Python38\site-packages\pandas\core\arraylike.py:402: RuntimeWarning:

divide by zero encountered in log

C:\Users\Akshat Mittu\AppData\Roaming\Python\Python38\site-packages\pandas\core\arraylike.py:402: RuntimeWarning:

divide by zero encountered in log

In [95]:
ks_results

{'Age': {'ks-stat': 0.09, 'ks_p-value': 0.21, 'ks_status': False},
 'RestingBP': {'ks-stat': 0.08, 'ks_p-value': 0.28, 'ks_status': False},
 'Cholesterol': {'ks-stat': 0.19, 'ks_p-value': 0.0, 'ks_status': True},
 'FastingBS': {'ks-stat': 0.09, 'ks_p-value': 0.17, 'ks_status': False},
 'MaxHR': {'ks-stat': 0.14, 'ks_p-value': 0.01, 'ks_status': True},
 'Oldpeak': {'ks-stat': 0.07, 'ks_p-value': 0.38, 'ks_status': False}}

In [96]:
chi_results

{'Sex': {'chi': 0.06, 'chi_p-value': 0.81, 'chi_status': True},
 'ChestPainType': {'chi': 7.5, 'chi_p-value': 0.59, 'chi_status': True},
 'RestingECG': {'chi': 0.99, 'chi_p-value': 0.91, 'chi_status': True},
 'ExerciseAngina': {'chi': 1.81, 'chi_p-value': 0.41, 'chi_status': True},
 'ST_Slope': {'chi': 2.83, 'chi_p-value': 0.59, 'chi_status': True}}

In [97]:
psi_results

{'Sex': {'psi_value': 0.05, 'psi_threshold': 0.2, 'psi_status': False},
 'ChestPainType': {'psi_value': 0.88,
  'psi_threshold': 0.2,
  'psi_status': True},
 'RestingECG': {'psi_value': 0.87, 'psi_threshold': 0.2, 'psi_status': True},
 'ExerciseAngina': {'psi_value': 0.89,
  'psi_threshold': 0.2,
  'psi_status': True},
 'ST_Slope': {'psi_value': 0.02, 'psi_threshold': 0.2, 'psi_status': False}}

In [98]:
js_results

{'Sex': {'jsd_value': 0.08, 'js_threshold': 0.2, 'js_status': False},
 'ChestPainType': {'jsd_value': 0.05, 'js_threshold': 0.2, 'js_status': False},
 'RestingECG': {'jsd_value': 0.02, 'js_threshold': 0.2, 'js_status': False},
 'ExerciseAngina': {'jsd_value': 0.17,
  'js_threshold': 0.2,
  'js_status': False},
 'ST_Slope': {'jsd_value': 0.05, 'js_threshold': 0.2, 'js_status': False}}

In [100]:
psi_num_results

{'Age': {'psi_value': 0.13, 'psi_threshold': 0.05, 'psi_status': True},
 'RestingBP': {'psi_value': inf, 'psi_threshold': 0.05, 'psi_status': True},
 'Cholesterol': {'psi_value': inf, 'psi_threshold': 0.05, 'psi_status': True},
 'FastingBS': {'psi_value': 0.0, 'psi_threshold': 0.05, 'psi_status': False},
 'MaxHR': {'psi_value': 0.14, 'psi_threshold': 0.05, 'psi_status': True},
 'Oldpeak': {'psi_value': inf, 'psi_threshold': 0.05, 'psi_status': True}}

In [101]:
js_results

{'Sex': {'jsd_value': 0.08, 'js_threshold': 0.2, 'js_status': False},
 'ChestPainType': {'jsd_value': 0.05, 'js_threshold': 0.2, 'js_status': False},
 'RestingECG': {'jsd_value': 0.02, 'js_threshold': 0.2, 'js_status': False},
 'ExerciseAngina': {'jsd_value': 0.17,
  'js_threshold': 0.2,
  'js_status': False},
 'ST_Slope': {'jsd_value': 0.05, 'js_threshold': 0.2, 'js_status': False}}

In [102]:
js_num_results

{'Age': {'jsd_value': 0.02, 'js_threshold': 0.1, 'js_status': False},
 'RestingBP': {'jsd_value': 0.01, 'js_threshold': 0.1, 'js_status': False},
 'Cholesterol': {'jsd_value': 0.02, 'js_threshold': 0.1, 'js_status': False},
 'FastingBS': {'jsd_value': 0.0, 'js_threshold': 0.1, 'js_status': False},
 'MaxHR': {'jsd_value': 0.02, 'js_threshold': 0.1, 'js_status': False},
 'Oldpeak': {'jsd_value': 0.01, 'js_threshold': 0.1, 'js_status': False}}

In [103]:
drift_num, drift_cat = pd.DataFrame(), pd.DataFrame()

In [114]:
drifting_nums = []
for i in num_ft:
    status = [ks_results[i]['ks_status'], js_num_results[i]['js_status'], psi_num_results[i]['psi_status']]
    
    if status.count(True) > status.count(False):
        drifting_nums.append(i)

In [115]:
drifting_nums

['Cholesterol', 'MaxHR']

In [122]:
ks_num = pd.DataFrame({'Feature Name': [i for i in drifting_nums],
                      'Test': ['KS-Test'] * len(drifting_nums),
                       'Statistic/Metric Value' : [ks_results[i]['ks-stat'] for i in drifting_nums],
                       'Threshold/Alpha': [0.05] * len(drifting_nums),
                      'P-value': [ks_results[i]['ks_p-value'] for i in drifting_nums],
                      'Test Status': [ks_results[i]['ks_status'] for i in drifting_nums]})

In [123]:
ks_num

,Feature Name,Test,Statistic/Metric Value,Threshold/Alpha,P-value,Test Status
0,Cholesterol,KS-Test,0.19,0.05,0.00,True
1,MaxHR,KS-Test,0.14,0.05,0.01,True

In [125]:
psi_num = pd.DataFrame({'Feature Name': [i for i in drifting_nums],
                      'Test': ['PSI'] * len(drifting_nums),
                       'Statistic/Metric Value' : [psi_num_results[i]['psi_value'] for i in drifting_nums],
                      'Threshold/Alpha': [psi_num_results[i]['psi_threshold'] for i in drifting_nums],
                        'P-value': [np.nan] * len(drifting_nums),
                      'Test Status': [psi_num_results[i]['psi_status'] for i in drifting_nums]})

In [126]:
psi_num

,Feature Name,Test,Statistic/Metric Value,Threshold/Alpha,P-value,Test Status
0,Cholesterol,PSI,inf,0.05,NaN,True
1,MaxHR,PSI,0.14,0.05,NaN,True

In [128]:
js_num = pd.DataFrame({'Feature Name': [i for i in drifting_nums],
                      'Test': ['JS Divergence'] * len(drifting_nums),
                       'Statistic/Metric Value' : [js_num_results[i]['jsd_value'] for i in drifting_nums],
                      'Threshold/Alpha': [js_num_results[i]['js_threshold'] for i in drifting_nums],
                        'P-value': [np.nan] * len(drifting_nums),
                      'Test Status': [js_num_results[i]['js_status'] for i in drifting_nums]})

In [129]:
js_num

,Feature Name,Test,Statistic/Metric Value,Threshold/Alpha,P-value,Test Status
0,Cholesterol,JS Divergence,0.02,0.1,NaN,False
1,MaxHR,JS Divergence,0.02,0.1,NaN,False

In [130]:
drift_num = pd.concat([ks_num, psi_num, js_num], axis=0)

In [131]:
drift_num

,Feature Name,Test,Statistic/Metric Value,Threshold/Alpha,P-value,Test Status
0,Cholesterol,KS-Test,0.19,0.05,0.00,True
1,MaxHR,KS-Test,0.14,0.05,0.01,True
0,Cholesterol,PSI,inf,0.05,NaN,True
1,MaxHR,PSI,0.14,0.05,NaN,True
0,Cholesterol,JS Divergence,0.02,0.10,NaN,False
1,MaxHR,JS Divergence,0.02,0.10,NaN,False

In [148]:
def get_drift_dfs(col_type, ks_results=None, chi_results=None, psi_results=None, psi_num_results=None, js_results=None, js_num_results=None, num_ft=None, cat_ft=None):
    
    
    if col_type == "numerical":
        
        drift_num, drifting_nums = pd.DataFrame(), []
        
        for i in num_ft:
            status = [ks_results[i]['ks_status'], js_num_results[i]['js_status'], psi_num_results[i]['psi_status']]

            if status.count(True) > status.count(False):
                drifting_nums.append(i)
        ks_num = pd.DataFrame({'Feature Name': [i for i in drifting_nums],
                      'Test': ['KS-Test'] * len(drifting_nums),
                       'Statistic/Metric Value' : [ks_results[i]['ks-stat'] for i in drifting_nums],
                       'Threshold/Alpha': [0.05] * len(drifting_nums),
                      'P-value': [ks_results[i]['ks_p-value'] for i in drifting_nums],
                      'Test Status': [ks_results[i]['ks_status'] for i in drifting_nums]})
    
        psi_num = pd.DataFrame({'Feature Name': [i for i in drifting_nums],
                          'Test': ['PSI'] * len(drifting_nums),
                           'Statistic/Metric Value' : [psi_num_results[i]['psi_value'] for i in drifting_nums],
                          'Threshold/Alpha': [psi_num_results[i]['psi_threshold'] for i in drifting_nums],
                            'P-value': [np.nan] * len(drifting_nums),
                          'Test Status': [psi_num_results[i]['psi_status'] for i in drifting_nums]})

        js_num = pd.DataFrame({'Feature Name': [i for i in drifting_nums],
                          'Test': ['JS Divergence'] * len(drifting_nums),
                           'Statistic/Metric Value' : [js_num_results[i]['jsd_value'] for i in drifting_nums],
                          'Threshold/Alpha': [js_num_results[i]['js_threshold'] for i in drifting_nums],
                            'P-value': [np.nan] * len(drifting_nums),
                          'Test Status': [js_num_results[i]['js_status'] for i in drifting_nums]})

        drift_num = pd.concat([ks_num, psi_num, js_num], axis=0)
        
        return drift_num, drifting_nums
        
    if col_type == "categorical":
        
        drifting_cats, drift_cat = [], pd.DataFrame()
        
        for i in cat_ft:
            status = [chi_results[i]['chi_status'], js_results[i]['js_status'], psi_results[i]['psi_status']]

            if status.count(True) > status.count(False):
                drifting_cats.append(i)

        chi = pd.DataFrame({'Feature Name': [i for i in drifting_cats],
                          'Test': ['Chi-Square Test'] * len(drifting_cats),
                           'Statistic/Metric Value' : [chi_results[i]['chi'] for i in drifting_cats],
                           'Threshold/Alpha': [0.05] * len(drifting_cats),
                          'P-value': [chi_results[i]['chi_p-value'] for i in drifting_cats],
                          'Test Status': [chi_results[i]['chi_status'] for i in drifting_cats]})

        psi_cat = pd.DataFrame({'Feature Name': [i for i in drifting_cats],
                          'Test': ['PSI'] * len(drifting_cats),
                           'Statistic/Metric Value' : [psi_results[i]['psi_value'] for i in drifting_cats],
                          'Threshold/Alpha': [psi_results[i]['psi_threshold'] for i in drifting_cats],
                            'P-value': [np.nan] * len(drifting_cats),
                          'Test Status': [psi_results[i]['psi_status'] for i in drifting_cats]})

        js_cat = pd.DataFrame({'Feature Name': [i for i in drifting_cats],
                          'Test': ['JS Divergence'] * len(drifting_cats),
                           'Statistic/Metric Value' : [js_results[i]['jsd_value'] for i in drifting_cats],
                          'Threshold/Alpha': [js_results[i]['js_threshold'] for i in drifting_cats],
                            'P-value': [np.nan] * len(drifting_cats),
                          'Test Status': [js_results[i]['js_status'] for i in drifting_cats]})

        drift_cat = pd.concat([chi, psi_cat, js_cat], axis=0)
    
    return drift_cat, drifting_cats

In [149]:
drift_num, drifting_nums = get_drift_dfs("numerical", ks_results=ks_results,  
                                        psi_num_results=psi_num_results, 
                                         js_num_results=js_num_results, 
                                        num_ft=numerical_ft)

In [151]:
drift_cat, drifting_cats = get_drift_dfs("categorical", chi_results=chi_results,  
                                        psi_results=psi_results, 
                                         js_results=js_results, 
                                        cat_ft=categorical_ft)

In [150]:
drift_num

,Feature Name,Test,Statistic/Metric Value,Threshold/Alpha,P-value,Test Status
0,Cholesterol,KS-Test,0.19,0.05,0.00,True
1,MaxHR,KS-Test,0.14,0.05,0.01,True
0,Cholesterol,PSI,inf,0.05,NaN,True
1,MaxHR,PSI,0.14,0.05,NaN,True
0,Cholesterol,JS Divergence,0.02,0.10,NaN,False
1,MaxHR,JS Divergence,0.02,0.10,NaN,False

In [152]:
drift_cat

,Feature Name,Test,Statistic/Metric Value,Threshold/Alpha,P-value,Test Status
0,ChestPainType,Chi-Square Test,7.50,0.05,0.59,True
1,RestingECG,Chi-Square Test,0.99,0.05,0.91,True
2,ExerciseAngina,Chi-Square Test,1.81,0.05,0.41,True
0,ChestPainType,PSI,0.88,0.20,NaN,True
1,RestingECG,PSI,0.87,0.20,NaN,True
2,ExerciseAngina,PSI,0.89,0.20,NaN,True
0,ChestPainType,JS Divergence,0.05,0.20,NaN,False
1,RestingECG,JS Divergence,0.02,0.20,NaN,False
2,ExerciseAngina,JS Divergence,0.17,0.20,NaN,False

In [153]:
drifting_nums, drifting_cats

(['Cholesterol', 'MaxHR'], ['ChestPainType', 'RestingECG', 'ExerciseAngina'])