In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd
import json
from utils import get_results

In [3]:
results_dict = {'Heart Disease Prediction': {'07th Feb 2024': {'Production Data Summary': {'num_of_rows': 209,
    'no_of_rows_without_nan': 171,
    'no_of_rows_with_nan': 38,
    'completeness_score': 81.82,
    'uniqueness_score': 100.0,
    'no_of_rows_without_duplicates': 209,
    'no_of_rows_with_duplicates': 0,
    'validity_score': 74.16,
    'total_num_of_invalidrows': 54,
    'Metrics': {'Accuracy': 87.56,
     'Precision': 90.0,
     'Recall': 88.52,
     'F1': 89.26,
     'ROC_AUC': 87.37,
     'False Positive Rate': 13.79},
    'Drifting Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']},
   'Input Feature Details': {'Age': {'num_of_missing_values': 0,
     'uniqueness_score': 20.1,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 52.66,
     'median': 54.0,
     'std': 9.53,
     'min': 28,
     'max': 76,
     'iqr': 13.0,
     'type': 'int64',
     'ks-stat': 0.09,
     'p-value': 0.21,
     'status': False},
    'Sex': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'M',
     'value_counts': {'M': 177, 'F': 32},
     'type': 'object',
     'chi': 0.06,
     'p-value': 0.81,
     'status': True},
    'ChestPainType': {'num_of_missing_values': 16,
     'uniqueness_score': 1.91,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'ASY',
     'value_counts': {'ASY': 100, 'NAP': 42, 'ATA': 36, 'TA': 15},
     'type': 'object',
     'chi': 7.5,
     'p-value': 0.59,
     'status': True},
    'RestingBP': {'num_of_missing_values': 16,
     'uniqueness_score': 22.01,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 3,
     'mean': 129.8,
     'median': 130.0,
     'std': 18.35,
     'min': 80.0,
     'max': 192.0,
     'iqr': 20.0,
     'type': 'float64',
     'ks-stat': 0.08,
     'p-value': 0.28,
     'status': False},
    'Cholesterol': {'num_of_missing_values': 38,
     'uniqueness_score': 45.45,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 2,
     'mean': 186.86,
     'median': 219.0,
     'std': 113.14,
     'min': 0.0,
     'max': 564.0,
     'iqr': 108.0,
     'type': 'float64',
     'ks-stat': 0.19,
     'p-value': 0.0,
     'status': True},
    'FastingBS': {'num_of_missing_values': 16,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 0.26,
     'median': 0.0,
     'std': 0.44,
     'min': 0.0,
     'max': 1.0,
     'iqr': 1.0,
     'type': 'float64',
     'ks-stat': 0.09,
     'p-value': 0.17,
     'status': False},
    'RestingECG': {'num_of_missing_values': 16,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Normal',
     'value_counts': {'Normal': 118, 'ST': 38, 'LVH': 37},
     'type': 'object',
     'chi': 0.99,
     'p-value': 0.91,
     'status': True},
    'MaxHR': {'num_of_missing_values': 16,
     'uniqueness_score': 38.76,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 1,
     'mean': 138.81,
     'median': 138.0,
     'std': 26.36,
     'min': 60.0,
     'max': 195.0,
     'iqr': 38.0,
     'type': 'float64',
     'ks-stat': 0.14,
     'p-value': 0.01,
     'status': True},
    'ExerciseAngina': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 16,
     'num_of_outliers': 0,
     'mode': 'N',
     'value_counts': {'N': 124, 'Y': 69, '1': 16},
     'type': 'object',
     'chi': 1.81,
     'p-value': 0.41,
     'status': True},
    'Oldpeak': {'num_of_missing_values': 0,
     'uniqueness_score': 16.75,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 2,
     'mean': 0.79,
     'median': 0.5,
     'std': 0.97,
     'min': -1.1,
     'max': 4.0,
     'iqr': 1.5,
     'type': 'float64',
     'ks-stat': 0.07,
     'p-value': 0.38,
     'status': False},
    'ST_Slope': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Up',
     'value_counts': {'Up': 97, 'Flat': 94, 'Down': 18},
     'type': 'object',
     'chi': 2.83,
     'p-value': 0.59,
     'status': True}},
   'Output Feature Details': {'chi': 112.96,
    'p-value': 0.0,
    'status': False}}}}

In [4]:
with open("results.json", "w") as f:
    json.dump(results_dict, f)

In [19]:
with open("results.json", "r") as res:
    results = json.load(res)

In [20]:
results

{'Heart Disease Prediction': {'07th Feb 2024': {'Production Data Summary': {'num_of_rows': 209,
    'no_of_rows_without_nan': 171,
    'no_of_rows_with_nan': 38,
    'completeness_score': 81.82,
    'uniqueness_score': 100.0,
    'no_of_rows_without_duplicates': 209,
    'no_of_rows_with_duplicates': 0,
    'validity_score': 74.16,
    'total_num_of_invalidrows': 54,
    'Metrics': {'Accuracy': 87.56,
     'Precision': 90.0,
     'Recall': 88.52,
     'F1': 89.26,
     'ROC_AUC': 87.37,
     'False Positive Rate': 13.79},
    'Drifting Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']},
   'Input Feature Details': {'Age': {'num_of_missing_values': 0,
     'uniqueness_score': 20.1,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 52.66,
     'median': 54.0,
     'std': 9.53,
     'min': 28,
     'max': 76,
     'iqr': 13.0,
     'type': 'int64',
     'ks-stat': 0.09,
     'p-value': 0.21,
     'status': False},
    'Sex': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'M',
     'value_counts': {'M': 177, 'F': 32},
     'type': 'object',
     'chi': 0.06,
     'p-value': 0.81,
     'status': True},
    'ChestPainType': {'num_of_missing_values': 16,
     'uniqueness_score': 1.91,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'ASY',
     'value_counts': {'ASY': 100, 'NAP': 42, 'ATA': 36, 'TA': 15},
     'type': 'object',
     'chi': 7.5,
     'p-value': 0.59,
     'status': True},
    'RestingBP': {'num_of_missing_values': 16,
     'uniqueness_score': 22.01,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 3,
     'mean': 129.8,
     'median': 130.0,
     'std': 18.35,
     'min': 80.0,
     'max': 192.0,
     'iqr': 20.0,
     'type': 'float64',
     'ks-stat': 0.08,
     'p-value': 0.28,
     'status': False},
    'Cholesterol': {'num_of_missing_values': 38,
     'uniqueness_score': 45.45,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 2,
     'mean': 186.86,
     'median': 219.0,
     'std': 113.14,
     'min': 0.0,
     'max': 564.0,
     'iqr': 108.0,
     'type': 'float64',
     'ks-stat': 0.19,
     'p-value': 0.0,
     'status': True},
    'FastingBS': {'num_of_missing_values': 16,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 0.26,
     'median': 0.0,
     'std': 0.44,
     'min': 0.0,
     'max': 1.0,
     'iqr': 1.0,
     'type': 'float64',
     'ks-stat': 0.09,
     'p-value': 0.17,
     'status': False},
    'RestingECG': {'num_of_missing_values': 16,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Normal',
     'value_counts': {'Normal': 118, 'ST': 38, 'LVH': 37},
     'type': 'object',
     'chi': 0.99,
     'p-value': 0.91,
     'status': True},
    'MaxHR': {'num_of_missing_values': 16,
     'uniqueness_score': 38.76,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 1,
     'mean': 138.81,
     'median': 138.0,
     'std': 26.36,
     'min': 60.0,
     'max': 195.0,
     'iqr': 38.0,
     'type': 'float64',
     'ks-stat': 0.14,
     'p-value': 0.01,
     'status': True},
    'ExerciseAngina': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 16,
     'num_of_outliers': 0,
     'mode': 'N',
     'value_counts': {'N': 124, 'Y': 69, '1': 16},
     'type': 'object',
     'chi': 1.81,
     'p-value': 0.41,
     'status': True},
    'Oldpeak': {'num_of_missing_values': 0,
     'uniqueness_score': 16.75,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 2,
     'mean': 0.79,
     'median': 0.5,
     'std': 0.97,
     'min': -1.1,
     'max': 4.0,
     'iqr': 1.5,
     'type': 'float64',
     'ks-stat': 0.07,
     'p-value': 0.38,
     'status': False},
    'ST_Slope': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Up',
     'value_counts': {'Up': 97, 'Flat': 94, 'Down': 18},
     'type': 'object',
     'chi': 2.83,
     'p-value': 0.59,
     'status': True}},
   'Output Feature Details': {'chi': 112.96,
    'p-value': 0.0,
    'status': False}}}}

In [7]:
prod_run = "./Heart Disease Prediction/Production Runs/31st Jan 2024.csv"
gt = "./Heart Disease Prediction/Ground Truths/31st Jan 2024.csv"

In [8]:
prod_data = pd.read_csv(prod_run)
gt_data = pd.read_csv(gt)

In [9]:
prod_data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target,probs
0,61,M,ASY,160,0,1,ST,145,N,1.0,Flat,1,1.0
1,43,M,ASY,100,0,1,Normal,122,N,1.5,Down,1,1.0
2,52,M,ASY,108,233,1,Normal,147,N,0.1,Up,1,0.6
3,60,M,NAP,141,316,1,ST,122,Y,1.7,Flat,1,1.0
4,42,M,ASY,105,0,1,Normal,128,Y,-1.5,Down,1,1.0

In [10]:
gt_data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
0,61,M,ASY,160,0,1,ST,145,N,1.0,Flat,1
1,43,M,ASY,100,0,1,Normal,122,N,1.5,Down,1
2,52,M,ASY,108,233,1,Normal,147,N,0.1,Up,0
3,60,M,NAP,141,316,1,ST,122,Y,1.7,Flat,1
4,42,M,ASY,105,0,1,Normal,128,Y,-1.5,Down,1

In [11]:
baseline = pd.read_csv("./Heart Disease Prediction/baseline.csv")

In [12]:
baseline.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,target
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
3,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
4,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0

In [14]:
new_results = get_results("Heart Disease Prediction", "31st Jan 2024", ground_truth=gt_data, production_data=prod_data, baseline_data=baseline, model_type="Classification")

{'target': {0: 94, 1: 115}} {'target': {0: 98, 1: 111}}
{'Sex': {'M': 381, 'F': 119}} {'Sex': {'M': 167, 'F': 42}}
{'ChestPainType': {'NAP': 118, 'ATA': 86, 'ASY': 272, 'TA': 24}} {'ChestPainType': {'NAP': 37, 'ATA': 49, 'ASY': 116, 'TA': 7}}
{'RestingECG': {'LVH': 109, 'Normal': 291, 'ST': 100}} {'RestingECG': {'LVH': 37, 'Normal': 133, 'ST': 39}}
{'ExerciseAngina': {'N': 285, 'Y': 215}} {'ExerciseAngina': {'N': 130, 'Y': 79}}
{'ST_Slope': {'Down': 36, 'Flat': 263, 'Up': 201}} {'ST_Slope': {'Down': 9, 'Flat': 103, 'Up': 97}}

In [15]:
new_results

{'Heart Disease Prediction': {'31st Jan 2024': {'Production Data Summary': {'num_of_rows': 209,
    'no_of_rows_without_nan': 209,
    'no_of_rows_with_nan': 0,
    'completeness_score': 100.0,
    'uniqueness_score': 100.0,
    'no_of_rows_without_duplicates': 209,
    'no_of_rows_with_duplicates': 0,
    'validity_score': 100.0,
    'total_num_of_invalidrows': 0,
    'Metrics': {'report': {'0': {'precision': 0.8367346938775511,
       'recall': 0.8723404255319149,
       'f1-score': 0.8541666666666667,
       'support': 94},
      '1': {'precision': 0.8918918918918919,
       'recall': 0.8608695652173913,
       'f1-score': 0.8761061946902654,
       'support': 115},
      'accuracy': 0.8660287081339713,
      'macro avg': {'precision': 0.8643132928847215,
       'recall': 0.8666049953746531,
       'f1-score': 0.8651364306784661,
       'support': 209},
      'weighted avg': {'precision': 0.8670843482873558,
       'recall': 0.8660287081339713,
       'f1-score': 0.8662386557705607,
       'support': 209}},
     'Accuracy': 86.6,
     'Precision': 89.19,
     'Recall': 86.09,
     'F1': 87.61,
     'ROC_AUC': 86.66,
     'False Positive Rate': 12.77},
    'Drifting Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']},
   'Input Feature Details': {'Age': {'num_of_missing_values': 0,
     'uniqueness_score': 20.57,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 52.95,
     'median': 53.0,
     'std': 9.47,
     'min': 29,
     'max': 77,
     'iqr': 14.0,
     'type': 'int64',
     'ks-stat': 0.11,
     'p-value': 0.04,
     'status': True},
    'Sex': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'M',
     'value_counts': {'M': 167, 'F': 42},
     'type': 'object',
     'chi': 3.91,
     'p-value': 0.05,
     'status': False},
    'ChestPainType': {'num_of_missing_values': 0,
     'uniqueness_score': 1.91,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'ASY',
     'value_counts': {'ASY': 116, 'ATA': 49, 'NAP': 37, 'TA': 7},
     'type': 'object',
     'chi': 3.98,
     'p-value': 0.91,
     'status': True},
    'RestingBP': {'num_of_missing_values': 0,
     'uniqueness_score': 20.1,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 132.04,
     'median': 130.0,
     'std': 17.36,
     'min': 100,
     'max': 190,
     'iqr': 20.0,
     'type': 'int64',
     'ks-stat': 0.08,
     'p-value': 0.31,
     'status': False},
    'Cholesterol': {'num_of_missing_values': 0,
     'uniqueness_score': 53.11,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 198.61,
     'median': 220.0,
     'std': 106.35,
     'min': 0,
     'max': 468,
     'iqr': 91.0,
     'type': 'int64',
     'ks-stat': 0.05,
     'p-value': 0.86,
     'status': False},
    'FastingBS': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 0.22,
     'median': 0.0,
     'std': 0.41,
     'min': 0,
     'max': 1,
     'iqr': 0.0,
     'type': 'int64',
     'ks-stat': 0.01,
     'p-value': 1.0,
     'status': False},
    'RestingECG': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Normal',
     'value_counts': {'Normal': 133, 'ST': 39, 'LVH': 37},
     'type': 'object',
     'chi': 7.73,
     'p-value': 0.1,
     'status': True},
    'MaxHR': {'num_of_missing_values': 0,
     'uniqueness_score': 37.32,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 137.89,
     'median': 140.0,
     'std': 24.58,
     'min': 84,
     'max': 202,
     'iqr': 35.0,
     'type': 'int64',
     'ks-stat': 0.05,
     'p-value': 0.8,
     'status': False},
    'ExerciseAngina': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'N',
     'value_counts': {'N': 130, 'Y': 79},
     'type': 'object',
     'chi': 0.02,
     'p-value': 0.88,
     'status': True},
    'Oldpeak': {'num_of_missing_values': 0,
     'uniqueness_score': 14.35,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 0.72,
     'median': 0.1,
     'std': 1.02,
     'min': -2.6,
     'max': 4.0,
     'iqr': 1.5,
     'type': 'float64',
     'ks-stat': 0.14,
     'p-value': 0.01,
     'status': True},
    'ST_Slope': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Flat',
     'value_counts': {'Flat': 103, 'Up': 97, 'Down': 9},
     'type': 'object',
     'chi': 4.33,
     'p-value': 0.36,
     'status': True}},
   'Output Feature Details': {'chi': 108.73,
    'p-value': 0.0,
    'status': False}}}}

In [21]:
results['Heart Disease Prediction'].update(new_results["Heart Disease Prediction"])

In [22]:
results

{'Heart Disease Prediction': {'07th Feb 2024': {'Production Data Summary': {'num_of_rows': 209,
    'no_of_rows_without_nan': 171,
    'no_of_rows_with_nan': 38,
    'completeness_score': 81.82,
    'uniqueness_score': 100.0,
    'no_of_rows_without_duplicates': 209,
    'no_of_rows_with_duplicates': 0,
    'validity_score': 74.16,
    'total_num_of_invalidrows': 54,
    'Metrics': {'Accuracy': 87.56,
     'Precision': 90.0,
     'Recall': 88.52,
     'F1': 89.26,
     'ROC_AUC': 87.37,
     'False Positive Rate': 13.79},
    'Drifting Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']},
   'Input Feature Details': {'Age': {'num_of_missing_values': 0,
     'uniqueness_score': 20.1,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 52.66,
     'median': 54.0,
     'std': 9.53,
     'min': 28,
     'max': 76,
     'iqr': 13.0,
     'type': 'int64',
     'ks-stat': 0.09,
     'p-value': 0.21,
     'status': False},
    'Sex': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'M',
     'value_counts': {'M': 177, 'F': 32},
     'type': 'object',
     'chi': 0.06,
     'p-value': 0.81,
     'status': True},
    'ChestPainType': {'num_of_missing_values': 16,
     'uniqueness_score': 1.91,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'ASY',
     'value_counts': {'ASY': 100, 'NAP': 42, 'ATA': 36, 'TA': 15},
     'type': 'object',
     'chi': 7.5,
     'p-value': 0.59,
     'status': True},
    'RestingBP': {'num_of_missing_values': 16,
     'uniqueness_score': 22.01,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 3,
     'mean': 129.8,
     'median': 130.0,
     'std': 18.35,
     'min': 80.0,
     'max': 192.0,
     'iqr': 20.0,
     'type': 'float64',
     'ks-stat': 0.08,
     'p-value': 0.28,
     'status': False},
    'Cholesterol': {'num_of_missing_values': 38,
     'uniqueness_score': 45.45,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 2,
     'mean': 186.86,
     'median': 219.0,
     'std': 113.14,
     'min': 0.0,
     'max': 564.0,
     'iqr': 108.0,
     'type': 'float64',
     'ks-stat': 0.19,
     'p-value': 0.0,
     'status': True},
    'FastingBS': {'num_of_missing_values': 16,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 0.26,
     'median': 0.0,
     'std': 0.44,
     'min': 0.0,
     'max': 1.0,
     'iqr': 1.0,
     'type': 'float64',
     'ks-stat': 0.09,
     'p-value': 0.17,
     'status': False},
    'RestingECG': {'num_of_missing_values': 16,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Normal',
     'value_counts': {'Normal': 118, 'ST': 38, 'LVH': 37},
     'type': 'object',
     'chi': 0.99,
     'p-value': 0.91,
     'status': True},
    'MaxHR': {'num_of_missing_values': 16,
     'uniqueness_score': 38.76,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 1,
     'mean': 138.81,
     'median': 138.0,
     'std': 26.36,
     'min': 60.0,
     'max': 195.0,
     'iqr': 38.0,
     'type': 'float64',
     'ks-stat': 0.14,
     'p-value': 0.01,
     'status': True},
    'ExerciseAngina': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 16,
     'num_of_outliers': 0,
     'mode': 'N',
     'value_counts': {'N': 124, 'Y': 69, '1': 16},
     'type': 'object',
     'chi': 1.81,
     'p-value': 0.41,
     'status': True},
    'Oldpeak': {'num_of_missing_values': 0,
     'uniqueness_score': 16.75,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 2,
     'mean': 0.79,
     'median': 0.5,
     'std': 0.97,
     'min': -1.1,
     'max': 4.0,
     'iqr': 1.5,
     'type': 'float64',
     'ks-stat': 0.07,
     'p-value': 0.38,
     'status': False},
    'ST_Slope': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Up',
     'value_counts': {'Up': 97, 'Flat': 94, 'Down': 18},
     'type': 'object',
     'chi': 2.83,
     'p-value': 0.59,
     'status': True}},
   'Output Feature Details': {'chi': 112.96, 'p-value': 0.0, 'status': False}},
  '31st Jan 2024': {'Production Data Summary': {'num_of_rows': 209,
    'no_of_rows_without_nan': 209,
    'no_of_rows_with_nan': 0,
    'completeness_score': 100.0,
    'uniqueness_score': 100.0,
    'no_of_rows_without_duplicates': 209,
    'no_of_rows_with_duplicates': 0,
    'validity_score': 100.0,
    'total_num_of_invalidrows': 0,
    'Metrics': {'report': {'0': {'precision': 0.8367346938775511,
       'recall': 0.8723404255319149,
       'f1-score': 0.8541666666666667,
       'support': 94},
      '1': {'precision': 0.8918918918918919,
       'recall': 0.8608695652173913,
       'f1-score': 0.8761061946902654,
       'support': 115},
      'accuracy': 0.8660287081339713,
      'macro avg': {'precision': 0.8643132928847215,
       'recall': 0.8666049953746531,
       'f1-score': 0.8651364306784661,
       'support': 209},
      'weighted avg': {'precision': 0.8670843482873558,
       'recall': 0.8660287081339713,
       'f1-score': 0.8662386557705607,
       'support': 209}},
     'Accuracy': 86.6,
     'Precision': 89.19,
     'Recall': 86.09,
     'F1': 87.61,
     'ROC_AUC': 86.66,
     'False Positive Rate': 12.77},
    'Drifting Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']},
   'Input Feature Details': {'Age': {'num_of_missing_values': 0,
     'uniqueness_score': 20.57,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 52.95,
     'median': 53.0,
     'std': 9.47,
     'min': 29,
     'max': 77,
     'iqr': 14.0,
     'type': 'int64',
     'ks-stat': 0.11,
     'p-value': 0.04,
     'status': True},
    'Sex': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'M',
     'value_counts': {'M': 167, 'F': 42},
     'type': 'object',
     'chi': 3.91,
     'p-value': 0.05,
     'status': False},
    'ChestPainType': {'num_of_missing_values': 0,
     'uniqueness_score': 1.91,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'ASY',
     'value_counts': {'ASY': 116, 'ATA': 49, 'NAP': 37, 'TA': 7},
     'type': 'object',
     'chi': 3.98,
     'p-value': 0.91,
     'status': True},
    'RestingBP': {'num_of_missing_values': 0,
     'uniqueness_score': 20.1,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 132.04,
     'median': 130.0,
     'std': 17.36,
     'min': 100,
     'max': 190,
     'iqr': 20.0,
     'type': 'int64',
     'ks-stat': 0.08,
     'p-value': 0.31,
     'status': False},
    'Cholesterol': {'num_of_missing_values': 0,
     'uniqueness_score': 53.11,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 198.61,
     'median': 220.0,
     'std': 106.35,
     'min': 0,
     'max': 468,
     'iqr': 91.0,
     'type': 'int64',
     'ks-stat': 0.05,
     'p-value': 0.86,
     'status': False},
    'FastingBS': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 0.22,
     'median': 0.0,
     'std': 0.41,
     'min': 0,
     'max': 1,
     'iqr': 0.0,
     'type': 'int64',
     'ks-stat': 0.01,
     'p-value': 1.0,
     'status': False},
    'RestingECG': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Normal',
     'value_counts': {'Normal': 133, 'ST': 39, 'LVH': 37},
     'type': 'object',
     'chi': 7.73,
     'p-value': 0.1,
     'status': True},
    'MaxHR': {'num_of_missing_values': 0,
     'uniqueness_score': 37.32,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 137.89,
     'median': 140.0,
     'std': 24.58,
     'min': 84,
     'max': 202,
     'iqr': 35.0,
     'type': 'int64',
     'ks-stat': 0.05,
     'p-value': 0.8,
     'status': False},
    'ExerciseAngina': {'num_of_missing_values': 0,
     'uniqueness_score': 0.96,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'N',
     'value_counts': {'N': 130, 'Y': 79},
     'type': 'object',
     'chi': 0.02,
     'p-value': 0.88,
     'status': True},
    'Oldpeak': {'num_of_missing_values': 0,
     'uniqueness_score': 14.35,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mean': 0.72,
     'median': 0.1,
     'std': 1.02,
     'min': -2.6,
     'max': 4.0,
     'iqr': 1.5,
     'type': 'float64',
     'ks-stat': 0.14,
     'p-value': 0.01,
     'status': True},
    'ST_Slope': {'num_of_missing_values': 0,
     'uniqueness_score': 1.44,
     'num_of_datatype_mismatch': 0,
     'num_of_outliers': 0,
     'mode': 'Flat',
     'value_counts': {'Flat': 103, 'Up': 97, 'Down': 9},
     'type': 'object',
     'chi': 4.33,
     'p-value': 0.36,
     'status': True}},
   'Output Feature Details': {'chi': 108.73,
    'p-value': 0.0,
    'status': False}}}}

In [26]:
results['Heart Disease Prediction']['31st Jan 2024']

{'Production Data Summary': {'num_of_rows': 209,
  'no_of_rows_without_nan': 209,
  'no_of_rows_with_nan': 0,
  'completeness_score': 100.0,
  'uniqueness_score': 100.0,
  'no_of_rows_without_duplicates': 209,
  'no_of_rows_with_duplicates': 0,
  'validity_score': 100.0,
  'total_num_of_invalidrows': 0,
  'Metrics': {'report': {'0': {'precision': 0.8367346938775511,
     'recall': 0.8723404255319149,
     'f1-score': 0.8541666666666667,
     'support': 94},
    '1': {'precision': 0.8918918918918919,
     'recall': 0.8608695652173913,
     'f1-score': 0.8761061946902654,
     'support': 115},
    'accuracy': 0.8660287081339713,
    'macro avg': {'precision': 0.8643132928847215,
     'recall': 0.8666049953746531,
     'f1-score': 0.8651364306784661,
     'support': 209},
    'weighted avg': {'precision': 0.8670843482873558,
     'recall': 0.8660287081339713,
     'f1-score': 0.8662386557705607,
     'support': 209}},
   'Accuracy': 86.6,
   'Precision': 89.19,
   'Recall': 86.09,
   'F1': 87.61,
   'ROC_AUC': 86.66,
   'False Positive Rate': 12.77},
  'Drifting Metrics': ['Accuracy', 'ROC_AUC', 'False Positive Rate']},
 'Input Feature Details': {'Age': {'num_of_missing_values': 0,
   'uniqueness_score': 20.57,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mean': 52.95,
   'median': 53.0,
   'std': 9.47,
   'min': 29,
   'max': 77,
   'iqr': 14.0,
   'type': 'int64',
   'ks-stat': 0.11,
   'p-value': 0.04,
   'status': True},
  'Sex': {'num_of_missing_values': 0,
   'uniqueness_score': 0.96,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mode': 'M',
   'value_counts': {'M': 167, 'F': 42},
   'type': 'object',
   'chi': 3.91,
   'p-value': 0.05,
   'status': False},
  'ChestPainType': {'num_of_missing_values': 0,
   'uniqueness_score': 1.91,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mode': 'ASY',
   'value_counts': {'ASY': 116, 'ATA': 49, 'NAP': 37, 'TA': 7},
   'type': 'object',
   'chi': 3.98,
   'p-value': 0.91,
   'status': True},
  'RestingBP': {'num_of_missing_values': 0,
   'uniqueness_score': 20.1,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mean': 132.04,
   'median': 130.0,
   'std': 17.36,
   'min': 100,
   'max': 190,
   'iqr': 20.0,
   'type': 'int64',
   'ks-stat': 0.08,
   'p-value': 0.31,
   'status': False},
  'Cholesterol': {'num_of_missing_values': 0,
   'uniqueness_score': 53.11,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mean': 198.61,
   'median': 220.0,
   'std': 106.35,
   'min': 0,
   'max': 468,
   'iqr': 91.0,
   'type': 'int64',
   'ks-stat': 0.05,
   'p-value': 0.86,
   'status': False},
  'FastingBS': {'num_of_missing_values': 0,
   'uniqueness_score': 0.96,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mean': 0.22,
   'median': 0.0,
   'std': 0.41,
   'min': 0,
   'max': 1,
   'iqr': 0.0,
   'type': 'int64',
   'ks-stat': 0.01,
   'p-value': 1.0,
   'status': False},
  'RestingECG': {'num_of_missing_values': 0,
   'uniqueness_score': 1.44,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mode': 'Normal',
   'value_counts': {'Normal': 133, 'ST': 39, 'LVH': 37},
   'type': 'object',
   'chi': 7.73,
   'p-value': 0.1,
   'status': True},
  'MaxHR': {'num_of_missing_values': 0,
   'uniqueness_score': 37.32,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mean': 137.89,
   'median': 140.0,
   'std': 24.58,
   'min': 84,
   'max': 202,
   'iqr': 35.0,
   'type': 'int64',
   'ks-stat': 0.05,
   'p-value': 0.8,
   'status': False},
  'ExerciseAngina': {'num_of_missing_values': 0,
   'uniqueness_score': 0.96,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mode': 'N',
   'value_counts': {'N': 130, 'Y': 79},
   'type': 'object',
   'chi': 0.02,
   'p-value': 0.88,
   'status': True},
  'Oldpeak': {'num_of_missing_values': 0,
   'uniqueness_score': 14.35,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mean': 0.72,
   'median': 0.1,
   'std': 1.02,
   'min': -2.6,
   'max': 4.0,
   'iqr': 1.5,
   'type': 'float64',
   'ks-stat': 0.14,
   'p-value': 0.01,
   'status': True},
  'ST_Slope': {'num_of_missing_values': 0,
   'uniqueness_score': 1.44,
   'num_of_datatype_mismatch': 0,
   'num_of_outliers': 0,
   'mode': 'Flat',
   'value_counts': {'Flat': 103, 'Up': 97, 'Down': 9},
   'type': 'object',
   'chi': 4.33,
   'p-value': 0.36,
   'status': True}},
 'Output Feature Details': {'chi': 108.73, 'p-value': 0.0, 'status': False}}